app = "cd-bot"
primary_region = "sea"

[build]
dockerfile = "Dockerfile"

[env]
PORT = "8080"

[experimental]
auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace_period = "10s"
    restart_limit = 0
