app = "cd-bot"
primary_region = "sea"  # Updated from logs (sea region in your output)

kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile"

[mounts]
  source = "orders_data"
  destination = "/app/data"  # Match logs mount path

[[services]]
  protocol = "tcp"
  internal_port = 8080
  ports = [
    {
      port = 80
      handlers = ["http"]
      force_https = true
    },
    {
      port = 443
      handlers = ["http"]
    }
  ]

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
