app = "cd-bot"
primary_region = "sjc"  # Adjust to your actual region (check 'fly status')

kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile"

[mounts]
  source = "orders_data"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  ports = [
    {
      port = 80
      handlers = ["http"]
      force_https = true
    },
    {
      port = 443
      handlers = ["http"]
    }
  ]

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
